### ISSUE TITLE
go get -u ; go mod tidy

### ISSUE THREAD

**Issue by leonklingele** [jiftechnify/untypedconst#1]
Hey and thanks for the project! 😊

I'd love to get this into [golangci-lint](https://github.com/golangci/golangci-lint/issues/3478) but that requires the `golang.org/x/tools` dependency to be updated so it works with the latest version of Go.

Can you run a quick `go get -u ; go mod tidy` and push the changes?

**Comment by jiftechnify** [comment]
Thank you for putting up my project for golangci-lint, and apologize for the inactivity of the maintenance🙇‍♂

I'll update the dependency soon :smiley:

**Comment by jiftechnify** [comment]
I also:
- gave it a valid tag
- setup CI (running test on PR)
- wrote a meaningful README

to meet [the requirements](https://github.com/golangci/golangci-lint/pull/3527#issuecomment-1411259126).
